# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/Circle-CI-workshop

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run static analysis
          command: |
            . venv/bin/activate
            flake8 test_fizzbuzz.py

      - run:
          name: run test
          command: |
           . venv/bin/activate
           python test_fizzbuzz.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
